### ISSUE TITLE
Compling issue

### ISSUE THREAD

**Issue by fwag** [marpaia/alpaca-cpp-starter-template#1]
First I add to fix this:
https://github.com/fwag/alpaca-trade-api-cpp/commit/01b81e3707386ab3f4a092affbca88abe84c391b

then now I have following error:
In file included from external/com_github_marpaia_alpaca_trade_api_cpp/alpaca/streaming.cpp:1:0:
external/com_github_marpaia_alpaca_trade_api_cpp/alpaca/streaming.h:57:24: error: expected ')' before '<' token
   Handler(std::function<void(DataType)> on_trade_update, std::function<void(DataType)> on_account_update)

Could you kindly check ?
Regards
fwag

**Comment by marpaia** [comment]
This was a bug in the client library: https://github.com/marpaia/alpaca-trade-api-cpp/issues/4
I fixed it here: https://github.com/marpaia/alpaca-trade-api-cpp/commit/4256ddb76f01779d15471e5b54edeb9e4e7f1d89
And updated the rev of this starter kit here: https://github.com/marpaia/alpaca-cpp-starter-template/commit/41b173edc3d57341ca6c6a076caae6db504ca535

So hopefully you should be good to go now!
